@startuml Diagrama de Uso
left to right direction

actor Administrador as admin

rectangle "Sistema Gestion de Reservas" {
    
    usecase "Ver Reservas" as GR
    usecase "Ver Tutores" as GT
    usecase "Ver Estudiantes" as GE
    usecase "Informacion" as informacion

    usecase "Registrar Estudiante" as GER
    usecase "Modificar Estudiante" as GEM
    usecase "Eliminar Estudiante" as GEE
    usecase "Información Estudiante" as GEV
    usecase "Buscar Estudiante" as GEB

    usecase "Registrar Tutor" as GTR
    usecase "Modificar Tutor" as GTM
    usecase "Eliminar Tutor" as GTE
    usecase "Información Tutor" as GTV
    usecase "Buscar Tutor" as GTB

    usecase "Registrar Reserva" as GRR
    usecase "Modificar Reserva" as GRM
    usecase "Eliminar Reserva" as GRE
    usecase "Información Reserva" as GRV
    usecase "Filtrar Reserva" as GRF

    usecase "Ver Calendario Reservas Tutor" as CT
    usecase "Ver calendario Reservas Estudiante" as CE
    usecase "Calendario Reservas" as CR

    usecase "Agregar/Quitar Materia" as TAQM
    usecase "Agregar/Quitar Disponibilidad" as TAQD

    usecase "Agregar/Quitar Estudiantes" as RAQE
}


admin --> GE
admin --> GT
admin --> GR
admin --> informacion

GE <.. GER : <<extend>>
GE <.. GEM : <<extend>>
GE <.. GEE : <<extend>>
GE <.. GEV : <<extend>>
GE <.right. GEB : <<extend>>

GT <.. GTR : <<extend>>
GT <.. GTM : <<extend>>
GT <.. GTE : <<extend>>
GT <.. GTV : <<extend>>
GT <.right. GTB : <<extend>>

GR <.. GRR : <<extend>>
GR <.. GRM : <<extend>>
GR <.. GRE : <<extend>>
GR <.. GRV : <<extend>>
GR <.right. GRF : <<extend>>

GTV ..> CT : <<include>>
GEV ..> CE : <<include>>
GRV ..> CR : <<include>>

GTM <.. TAQM : <<extend>>
GTM <.. TAQD : <<extend>>

GRM <.. RAQE : <<extend>>

@enduml
